
import './globals.css'
import DataProvider from "./components/Navbar/DataProvider"
import {Marhey} from 'next/font/google'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Raleway}  from 'next/font/google'



const raleway = Raleway({
  weight: ["500","600","700"],
  subsets: ['latin'],
  variable: '--font-raleway',
})



const marhey = Marhey({
  weight: '700',
  subsets: ['arabic'],
  variable: '--font-marhey',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ToDo List App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${marhey.variable} ${raleway.variable}`}>
      <body className={inter.className}>
        <DataProvider>
        {children}
        </DataProvider>
        </body>
    </html>
  )
}
